# Generated by Django 3.2.7 on 2022-01-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_exoplanet_atmosphere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('star', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.star')),
            ],
        ),
    ]
